stages:
  - dependencies
  - build
  - release

dependencies:
  stage: dependencies
  artifacts:
    paths:
      - node_modules
  script:
    - npm install
  only:
    - tags

build:
  stage: build
  artifacts:
    paths:
      - dist
  script:
    - npm run build
  only:
    - tags

release:
  stage: release
  script:
    - TAG=( ${CI_BUILD_TAG//[-.]/ } )
    - if [[ ${TAG[0]} =~ [0-9]+ ]] ; then MAJOR=${TAG[0]}; else MAJOR=${TAG[1]}; fi
    - docker login -u builder -p $BUILDER_TOKEN docker.viriciti.com
    - docker build --build-arg GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN} $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:${MAJOR}
    - docker push $CI_REGISTRY_IMAGE:${MAJOR}
  only:
    - tags
