export const SELECT_DEVICE = '@constants/SELECT_DEVICE'

export const UPDATE_APPLICATION_ACTIVITY = '@constants/UPDATE_APPLICATION_ACTIVITY'
export const UPDATE_DEVICE_ACTIVITY = '@constants/UPDATE_DEVICE_ACTIVITY'
